first = input('What is your first name? ')
last = input('What is your last name? ')
email = input('What is your email address? ')
phone = input('What is your phone number? ')
job = input('What is your job title? ')
id = input('What is your ID number? ')
hair = input('What is your hair color? ')
eyes = input('What is your eye color? ')
month = input('What month did you start? ')
training = input('Did you complete your training? ')
print('')
print('Here is your ID Card: ')
print('----------------------------------------')
print(last.upper() + ', ' + first.capitalize())
print(job.title())
print('ID: ' + id)
print('')
print(email.lower())
print(phone)
print('')
print('Hair: {0:10}' 'Eyes: {1} '.format (hair.capitalize(), eyes.capitalize()))
print('Month: {0:10}' 'Training: {1} '.format (month.capitalize(), training.capitalize()))
print('----------------------------------------')