zero = input('Gimme a noun: ')
one = input('And another noun: ')
two = input('And another noun: ')
three = input('A verb: ')
four = input('A verb ending in "ing": ')
five = input('Now an adjective: ')
six = input('Another verb: ')
seven = input('A noun: ')
eight = input('Now a verb ending in "ing": ')
nine = input('Another verb ending in "ing": ')
output = ('You are a(n) {0}. \nYou are on your way to go eat a(n) {1} at a special {2} restaurant. \nOn your way, however, you were stopped in the street by many strangers. \nThe strangers asked you: why is there a {0} going to a {2} restaurant? \nYou are confused as to how they know you are on your way to a {2} restaurant, but decide to let it slide. \nYou reply to the strangers: Because I want {1}. \nThe strangers {3} in unison and start {4} at you. \nYou run back home in tears, wondering what you did to deserve such {5}. \nA few days later, you decide to try again. \nYou need that delicious {1} at the {2} restaurant. \nYou pass by the strangers once again, and they try to stop you, but you {6} right through them, yelling: I will call the {7} if you keep {4} at me! \nThe strangers immediately stop in their tracks, {8} themselves. \nYou keep going until you get to the {2} restaurant, and you start {9} with joy. \nThe end?'.format (zero, one, two, three, four, five, six, seven, eight, nine))
print('')
print(output)